### ISSUE TITLE
Add Support for Function Calls to T Language

### ISSUE THREAD

**Issue by travis-heavener** [travis-heavener/tpu2#5]
Improve the lexer and parser to support calling functions with arguments. The actual arguments passed to a function must also be dealt with in the t_assembler.cpp, since they're scoped variables. In the expression assembler when a function is met, just evaluate the expression inside for each argument, push them to the stack, and call the corresponding label after looking it up. After the end of the label is met, grab the return value out of DX and push that onto the stack in the expression assembler.

**Comment by travis-heavener** [comment]
WIP as of 01f43cf

**Comment by travis-heavener** [comment]
Added as of commit 4d59318, still need to force return on non-void functions, prevent invalid parameters being provided, and handle void as a return type.

**Comment by travis-heavener** [comment]
Improved in commit 0145bc8, working on forcing parameters, supporting void types, and confirming return sizing now.

**Comment by travis-heavener** [comment]
Also needed: prevent duplicate functions but allow distinction from arguments.

**Comment by travis-heavener** [comment]
Now supports void return (prevents using void return in expression) and forces return on non-void functions in bd3c953.

**Comment by heavet-rpi** [comment]
Finished implementation in 8a2f566.

**Comment by travis-heavener** [comment]
Implemented as of 8a2f566.
